smov_states:  
  # AVJG: 0.9 pour le rendre stable
  ros__parameters:
    #     Port, Center, Range,   Direction, Center angle, Minimum absolute value (Optional), Max absolute value (Optional)
    AVCG: [0,   315,    220,     -1,        90,           1,                                 1]
    AVCD: [15,  315,    220,     1,         90,           1,                                 1]
    AVBG: [1,   315,    440,     1,         1,            1,                                 1]
    AVBD: [14,  300,    440,     -1,        1,            1,                                 1]
    AVJG: [2,   315,    440,     -1,        1,            1,                                 1]
    AVJD: [13,  340,    390,     1,         1,            1,                                 1]
    ARBG: [14,  315,    440,     1,         1,            1,                                 1]
    ARBD: [1,   335,    440,     -1,        1,            1,                                 1]
    ARCG: [15,  315,    220,     1,         90,           1,                                 1]
    ARCD: [0,   315,    220,     -1,        90,           1,                                 1] 
    ARJG: [13,  315,    440,     -1,        1,            1,                                 1]
    ARJD: [2,   325 ,   390,     1,         1,            1,                                 1]

    pulse_for_angle: 2.38
