smov_states:  
  ros__parameters:
    # AVCG: Avant Corps Gauche (french).
    # Port, Center, Range, Direction, Minimum absolute value, Max absolute value, Center angle
    AVCG: [0, 333,1,1,1,1,90]
    AVCD: [15, 333,1,1,1,90]
    AVMG: [1, 333,1,1,1,1]
    AVMD: [14, 333,1,1,1,1]
    AVJG: [2, 333,1,1,1,1]
    AVJD: [13, 333,1,1,1,1]
    ARMG: [14, 333,1,1,1,1]
    ARMD: [1, 333,1,1,1,1]
    ARCG: [15, 333,1,1,1,90]
    ARCD: [0, 333,1,1,1,90] 
    ARJG: [13, 333,1,1,1,1]
    ARJD: [2, 333,1,1,1,1]
     